"""City-specific lending factors and FAQs for the locations/ pages.

Each factor and FAQ is tagged with the services it applies to, so pages for the
same city pull different subsets. Keep everything factual and NZ-specific: no
rates, no prices beyond city_data.py, no lender-specific promises.

Service keys: hl home-loan, fhb first-home-buyer, ip investment-property,
pa pre-approval, rf refinance, se self-employed.
"""

SERVICE_KEYS = {
    "home-loan": "hl",
    "first-home-buyer": "fhb",
    "investment-property": "ip",
    "pre-approval": "pa",
    "refinance": "rf",
    "self-employed": "se",
}

LOCAL = {
    "auckland-city": {
        "factors": [
            ("Apartments, unit titles and leasehold", "hl fhb ip pa",
             "Central Auckland has more apartments and unit-titled property than anywhere else in New Zealand, and lenders treat them very differently. Small studios, leasehold land, serviced or hotel-style units and buildings with weathertightness history can all need a bigger deposit or narrow the lender list. We check the title, body corporate minutes and long-term maintenance plan before you go unconditional, not after."),
            ("Townhouses and intensification", "hl fhb pa",
             "Auckland's Unitary Plan has turned many older sections into terraced and duplex townhouses. New builds can fall under the Reserve Bank's new-build exemption from LVR limits, which is why many first home buyers in Mt Albert, Avondale and Point Chevalier buy off the plans. The catch is that the bank values the property at settlement, not when you sign, so we plan for a valuation gap up front."),
            ("Flood and land-risk categories", "hl rf pa ip",
             "After the 2023 Anniversary Weekend floods, Auckland Council assessed affected homes into risk categories and insurers became more selective. Lenders need full replacement insurance before they settle, so a property with a flood history or overland flow path can stall late in the process. We ask for the LIM and an insurance quote early, especially in low-lying parts of the isthmus."),
            ("Debt-to-income limits bite hardest here", "hl fhb pa se",
             "Since July 2024 banks have worked within Reserve Bank debt-to-income limits, with a cap of six times income for owner-occupiers and a small allowance above it. At central Auckland prices that cap often binds before the deposit does. Structuring existing debts, choosing the right lender's DTI treatment and timing an application can make a real difference to the amount approved."),
            ("Investor yield versus capital growth", "ip rf",
             "Rental yields in central Auckland have historically been lower than in most regions, so investors here usually rely on serviceability from other income. With interest deductibility fully restored from April 2025 and the bright-line test back to two years, the numbers have shifted. We model each lender's rental income shading and test rates so you know your real headroom before making an offer."),
            ("Company and contractor income in the CBD", "se rf",
             "Many central Auckland borrowers are IT, consulting or professional contractors paid through their own company or on day rates. Main banks generally want two years of financials, but some lenders will assess contractors on current contract income with a shorter history. Knowing which lender reads your company accounts sympathetically is often worth more than a small difference in rate."),
            ("School zones and upgrade timing", "hl rf pa",
             "Buyers moving into central Auckland school zones often need to buy before they sell. Bridging finance, or a lender that will count a conditional sale, lets you secure the zoned home without losing it at auction. We line up the bridging terms and the end loan together so the exit is clear from the start."),
            ('Low-doc and non-bank pathways', 'se pa',
             'Auckland business owners who have just gone out on their own, or whose latest accounts show a dip, often fall outside main-bank policy. Non-bank lenders can use GST returns, accountant letters or a single year of figures, usually at a higher rate. We treat that as a stepping stone and plan the move back to a main bank once your accounts catch up.'),
        ],
        "faqs": [
            ("Will a bank lend on a small Auckland apartment?", "hl fhb ip pa",
             "Often yes, but the deposit and lender list depend on floor area, title type and the building's history. Very small studios, leasehold and serviced apartments are where main banks pull back most. We check these before you make an offer so you are not caught out at valuation."),
            ("Does the new-build exemption help in central Auckland?", "fhb pa hl",
             "Yes. Genuine new builds, including off-the-plan townhouses, are exempt from the Reserve Bank's LVR restrictions, so banks can lend at a lower deposit than for an existing home. Lender appetite and valuation risk at settlement still matter, so we plan for both."),
            ("How does flood risk affect my Auckland mortgage?", "rf hl ip",
             "Lenders will not settle without full insurance, and some insurers now load or decline homes with flood history or overland flow paths. We check the LIM and get an insurance indication early so it does not hold up your settlement or switch."),
            ("Is Auckland still worth it for property investors?", "ip",
             "It depends on your other income. Yields are lower than in many regions, so lenders lean on your wider serviceability. Restored interest deductibility helps, and we model each lender's rental assessment before you commit."),
            ("Can a contractor on a day rate borrow in Auckland?", "se pa",
             "Yes. Some lenders assess contractors on their current contract and recent history rather than two full years of company accounts. Which lender suits you depends on your contract length and how you pay yourself."),
            ("Can I refinance an Auckland apartment to a better rate?", "rf",
             "Usually, as long as the new lender is comfortable with the building and your equity. Unit title, leasehold and weathertightness issues can limit which lenders will take it on, so we check that first and only recommend a switch if it pays."),
            ('Does the DTI cap apply to self-employed buyers in Auckland?', 'se',
             'Yes. DTI limits apply to your total debt against your assessed income, so how a lender calculates self-employed income directly affects how much you can borrow. Lenders differ on add-backs and averaging, which is where choosing the right one matters.'),
        ],
    },
    "manukau": {
        "factors": [
            ("New-build growth from Flat Bush to Drury", "hl fhb pa ip",
             "South Auckland has some of the region's biggest greenfield growth areas, including Flat Bush, Takanini and the Drury corridor. New builds there can sit outside the Reserve Bank's LVR limits, which opens up lower-deposit options. House-and-land packages and off-the-plan purchases need careful staging, because the bank values the property at completion."),
            ("Extended families and shared ownership", "hl fhb pa",
             "Multi-generational households are common across Manukau, Māngere and Ōtara, and many buyers pool income or deposits with parents, siblings or adult children. Lenders handle co-borrowers, family guarantees and gifted deposits differently. Getting the ownership structure and the paperwork right at the start avoids problems at settlement and later on."),
            ("Overtime, shift and allowance income", "hl fhb pa se",
             "Many South Auckland households earn through shift work at the airport, in logistics, manufacturing or healthcare. Lenders differ widely on how much overtime, penal rates and allowances they will count, and over what history. Choosing a lender that recognises your real income can change your borrowing power noticeably."),
            ("Kāinga Ora and First Home Loan options", "fhb pa",
             "The Kāinga Ora First Home Loan lets eligible buyers borrow with a 5% deposit through participating lenders, subject to income and eligibility criteria. KiwiSaver first home withdrawals can top up the deposit. We check eligibility and which participating lender suits your income before you start bidding."),
            ("Flood history and insurance", "hl rf ip",
             "Parts of South Auckland were hit in the 2023 floods and some streets sit near overland flow paths or stormwater catchments. Lenders need full replacement insurance before settlement, so insurance availability can make or break a deal. We get an indication early and check the LIM for flood notes."),
            ("Small business and trade owners", "se rf",
             "Manukau has a large base of tradespeople, transport operators and family-run businesses. Main banks often want two years of financials, but non-bank lenders may use one year or accountant-prepared figures. We present your business numbers the way each lender assesses them, and look at consolidating business or vehicle debt where it helps."),
            ("Investor demand near transport links", "ip rf",
             "Rental demand in South Auckland stays solid near the Southern Motorway, rail stations and the airport employment zone. Investors are assessed on DTI limits and lender rental income shading, and newer townhouses can be easier to finance. We compare investor policy across lenders before you buy or restructure."),
            ('Family businesses and cash-heavy trades', 'se pa',
             'Many South Auckland businesses are family-run shops, food businesses or transport operators where income is split between family members or reinvested. Lenders need to see that income clearly in the accounts and tax returns. We work with your accountant so the figures reflect what the business really earns before we approach a lender.'),
        ],
        "faqs": [
            ("Can my parents help us buy in South Auckland?", "fhb hl pa",
             "Yes. Parents can gift a deposit, go guarantor on part of the loan, or co-own. Each option affects your borrowing and their risk differently, and lenders want specific documentation, so we set it up properly before you apply."),
            ("Will lenders count my overtime and shift allowances?", "hl fhb pa se",
             "Most lenders count some of it, usually based on a consistent history. How much they count varies a lot between lenders, so we choose the one that recognises your real pay."),
            ("Is a house-and-land package in Flat Bush or Drury a good first home?", "fhb hl",
             "It can be, because new builds are exempt from LVR limits, so lenders can accept a smaller deposit. The main risks are build delays and the bank's valuation at completion, which we plan around."),
            ("Can I refinance a South Auckland home with flood history?", "rf",
             "Usually, if the property can be insured. The new lender will want confirmation of cover, and some insurers are more cautious in flood-affected streets, so we check that before recommending a switch."),
            ("Do South Auckland rentals suit new investors?", "ip",
             "Rental demand is steady near transport and employment hubs. Lenders assess your total position under DTI limits, so we model the deal across several lenders first."),
            ("I'm self-employed in the trades. Can I still get a home loan?", "se pa",
             "Yes. Bank or non-bank, the right lender depends on how long you have been trading and how your income shows in your accounts. We match you to the lender that reads your numbers fairly."),
            ('Is it worth refinancing my South Auckland mortgage when my fixed rate ends?', 'rf',
             "Usually worth checking. Compare your bank's offer with other lenders at least a few weeks before the rollover, including any cashback and the cost of switching. We do that comparison and only recommend moving if the numbers work."),
            ('Can I use equity in my Manukau home to buy a rental?', 'ip',
             "Often yes. Equity in your home can fund the deposit for an investment property, subject to DTI limits and the lender's investor LVR rules. We model the structure across lenders first."),
        ],
    },
    "hamilton": {
        "factors": [
            ("Peacocke, Rototuna and Rotokauri growth", "hl fhb pa ip",
             "Hamilton's main growth areas, including Peacocke, Rototuna and Rotokauri, are full of new subdivisions. New builds are exempt from LVR limits, so first home buyers often get in with a smaller deposit than for an older house. We line up the build contract, the lender's progress payment rules and the valuation timing before you sign."),
            ("Lifestyle blocks around the Waikato", "hl rf ip pa",
             "Buyers drawn to lifestyle land around Tamahere, Matangi and Ngāruawāhia find lenders apply different rules. Larger blocks, properties with farming income or non-standard water and wastewater can fall outside standard residential policy. We know which lenders are comfortable with rural-residential property and how much land they will treat as residential."),
            ("Auckland commuters and remote workers", "hl fhb pa",
             "Since the Waikato Expressway opened end to end, more Auckland workers have bought in Hamilton and commute or work hybrid. Lenders look at where your employer is and how secure the arrangement is. We present remote and hybrid employment clearly so it is assessed on the same footing as a local job."),
            ("Student rentals near the university", "ip rf",
             "The University of Waikato and Wintec keep rental demand steady in Hillcrest, Silverdale and Claudelands. Student rentals have higher tenant turnover and must meet Healthy Homes standards. We compare investor lending policy and rental income assessment across lenders so your next purchase is properly structured."),
            ("Rural servicing and agri-business income", "se rf",
             "Many Hamilton self-employed borrowers work in agri-services, contracting, transport or rural trades with seasonal cashflow. Lenders read seasonal income and business add-backs differently. We present your accounts to lenders that understand rural business cycles, and look at restructuring business debt where it lowers your costs."),
            ("Older weatherboard homes", "fhb rf hl",
             "Hamilton's older suburbs have many 1950s to 1970s weatherboard homes that need insulation, heating or re-roofing. Some lenders will lend extra for renovations, and some first home buyers use a top-up after settlement. We factor in a builder's report and work out whether to fund the work now or later."),
            ('Contractors and farm-service businesses', 'se pa',
             'Hamilton has many sole traders and small companies servicing farms, building sites and the wider Waikato. Main banks usually want two years of financials. Some lenders will consider one year, or recent GST returns alongside the last full year. We match your trading history to the lender most likely to accept it.'),
            ('Self-employed equity and lifestyle land', 'se ip',
             'Business owners who also hold lifestyle or rental property often have equity spread across several titles. Lenders treat cross-securitised loans differently, and splitting them can give you more flexibility later. We review the structure when you buy or refinance.'),
        ],
        "faqs": [
            ("Can I buy a lifestyle block near Hamilton with a standard home loan?", "hl pa ip",
             "Often, if the land and income fit residential policy. Larger blocks or properties with farming income may need a rural or specialist lender. We check lender land-size rules before you make an offer."),
            ("Are Peacocke and Rototuna new builds good for first home buyers?", "fhb pa",
             "They can be, because new builds are exempt from LVR limits. The main risks are build timing and valuation at completion, which we plan for with the lender up front."),
            ("Will a lender count my Auckland job if I live in Hamilton?", "hl fhb pa",
             "Yes. What matters is that the employment is secure and the arrangement is documented. We make sure hybrid or remote work is presented clearly."),
            ("Do Hamilton student rentals make good investments?", "ip",
             "Demand is steady near the university and Wintec, but student rentals need Healthy Homes compliance and active management. We model each lender's rental assessment before you buy."),
            ("Should I refinance to fund renovations on my Hamilton home?", "rf",
             "If your equity supports it, a top-up or switch can fund insulation, heating or roofing at home-loan rates. We compare a top-up with your current bank against switching, after costs."),
            ("Can seasonal agri-business income qualify for a mortgage?", "se",
             "Yes, with the right lender. Some average your income over two years and accept seasonal patterns. We present your accounts to lenders that understand rural cashflow."),
            ('Can I refinance a Hamilton lifestyle block to a better lender?', 'rf',
             'Often, if the new lender is comfortable with the land size and services. Rural-residential policy varies, so we check before you incur switching costs.'),
            ('How long do I need to be self-employed to buy in Hamilton?', 'se',
             'Main banks generally want two years of trading. Some lenders accept one year or recent figures if you have a background in the same industry.'),
        ],
    },
    "tauranga": {
        "factors": [
            ("Prices that stretch local incomes", "hl fhb pa se",
             "Tauranga has long had some of New Zealand's highest house prices relative to local incomes. That means Reserve Bank debt-to-income limits often cap borrowing before the deposit does. Lender choice, how existing debts are structured and how each lender calculates DTI can all change how much you are approved for."),
            ("Downsizers, retirees and longer loan terms", "hl rf",
             "Many Bay of Plenty buyers are downsizing or moving for retirement. Lenders want a clear repayment plan when the loan term runs past your expected retirement age, such as the sale of another property, KiwiSaver or a shorter term. We present that exit plan up front so it does not hold up approval."),
            ("Coastal and liquefaction hazards", "hl fhb rf pa ip",
             "Tauranga City Council publishes hazard maps covering coastal inundation, flooding and liquefaction across Mount Maunganui, Pāpāmoa and parts of the harbour edge. These can show on the LIM and affect insurance and lender appetite. We review hazard notes early so they do not surprise you at the valuation stage."),
            ("Growth in Pāpāmoa East and Tauriko", "fhb hl pa ip",
             "New-build growth is concentrated in Pāpāmoa East, Tauriko and the western corridor. Because new builds are exempt from LVR limits, they can give first home buyers and investors a lower-deposit path. We plan the build contract, deposit and valuation timing with the lender before you commit."),
            ("Horticulture and seasonal income", "se pa",
             "Kiwifruit and avocado orchards around Te Puke and Katikati create seasonal and contract income, and many owners run their own businesses. Lenders differ in how they average seasonal earnings and accept orchard or contracting income. We match you to the lender whose policy suits your income pattern."),
            ("Port and logistics employment", "pa fhb ip",
             "The Port of Tauranga and the logistics businesses around it employ many shift workers. How lenders treat overtime, shift allowances and fixed-term roles varies. We gather the right payslip history so the lender counts your actual earnings."),
            ("Rental demand and investor structure", "ip rf",
             "Steady population growth has kept Tauranga rental demand firm, but yields are moderate compared with entry prices. Investors are assessed under DTI limits and lender rental shading. We compare lenders on investor policy and look at whether a restructure frees up equity for the next purchase."),
            ('Business owners and the DTI cap', 'se rf',
             'Tauranga has many self-employed borrowers in trades, horticulture services and small business. Because prices are high, how a lender assesses your business income under DTI limits often decides the outcome. We present add-backs and averaged income to the lender whose policy suits your accounts.'),
        ],
        "faqs": [
            ("Why is it harder to borrow enough in Tauranga?", "hl fhb pa",
             "Prices are high relative to local incomes, so DTI limits often cap borrowing before the deposit does. Lenders calculate DTI differently, which is where broker choice helps."),
            ("Can I get a mortgage close to retirement in Tauranga?", "hl rf",
             "Yes, if you show a clear plan to repay, such as selling another property, using KiwiSaver or choosing a shorter term. We set out that exit strategy for the lender up front."),
            ("Do coastal hazard notes on a Mount Maunganui LIM stop a mortgage?", "hl fhb pa ip",
             "Not usually on their own, but they can affect insurance and lender appetite. We check hazard notes and insurability early so the loan isn't held up."),
            ("Is a new build in Pāpāmoa East a good first home?", "fhb",
             "It can be, since new builds are exempt from LVR limits. We plan for build timing and the bank's valuation at completion."),
            ("Can orchard or kiwifruit contracting income get a home loan?", "se pa",
             "Yes. Some lenders average seasonal income over two years. We present your accounts to the lender whose policy fits."),
            ("Should Tauranga investors restructure their loans?", "ip rf",
             "If your equity has grown, restructuring can release funds for the next purchase or lower costs. We compare lenders on investor policy and the net benefit after any break fees."),
            ('Should I refinance my Tauranga mortgage when my fixed term ends?', 'rf',
             "It's worth comparing. Your bank's rollover offer is not always the sharpest. We compare lenders, including cashback and switching costs, and only recommend moving if it pays."),
            ('Can a self-employed Tauranga buyer borrow enough under DTI limits?', 'se',
             'It depends on how your income is assessed. Lenders treat add-backs and averaging differently, so lender choice often decides how much you can borrow.'),
        ],
    },
    "wellington": {
        "factors": [
            ("Earthquake-prone apartments", "hl fhb pa ip rf",
             "Wellington has many apartments in buildings with seismic ratings well below the new building standard. A unit in a building officially classed as earthquake-prone (below 34% NBS) can be very hard to finance, and many lenders also look closely at buildings just above that line. We check the seismic rating, any strengthening plans and body corporate levies before you commit."),
            ("Hillside sections, retaining walls and slips", "hl fhb pa",
             "Much of Wellington is built on steep land. Older retaining walls, slip history and unconsented work can show up on the LIM and builder's report and affect both insurance and lender appetite. We review these early so a late surprise doesn't derail the purchase."),
            ("Public sector and fixed-term roles", "hl fhb pa se",
             "A large share of Wellington borrowers work for government agencies, often on fixed-term or project contracts. Lenders differ on how long a contract must run and how they treat contractors moving between agencies. We present your employment history so it is assessed fairly."),
            ("Equity after the price correction", "rf hl",
             "Wellington had one of the sharpest price falls after the 2021 peak, so some recent buyers have less equity than they expected. Low equity limits who you can switch to. A restructure with your current bank or careful lender choice can still lower your costs, and we only recommend a switch if it pays after costs."),
            ("Hutt, Porirua and Kāpiti options", "fhb hl ip",
             "Many first home buyers and investors look past the city to Lower Hutt, Upper Hutt, Porirua and Kāpiti for more house for the money. Each area has its own flood, liquefaction and insurance considerations. We compare lenders across those suburbs, not just the central city."),
            ("Rental demand near universities and hospitals", "ip rf",
             "Victoria University, Wellington Hospital and the CBD support steady rental demand in Kelburn, Newtown, Mt Cook and Te Aro. Older villas need Healthy Homes upgrades, and investors are assessed under DTI limits. We model the deal across several lenders first."),
            ("Consultants and contractors", "se rf",
             "Many self-employed Wellingtonians are policy, IT or engineering consultants working on contract through their own companies. Some lenders accept a shorter trading history if the contract is ongoing. We match you to the lender that reads company or contractor income sympathetically."),
            ('Self-employed after public-sector change', 'se pa',
             'Some Wellingtonians have moved from public-sector roles into self-employment or consulting. Main banks usually want two years of trading, but some lenders will consider a shorter history if you are doing the same work you did as an employee. We find the lender that recognises that continuity.'),
        ],
        "faqs": [
            ("Can I get a mortgage on an earthquake-prone apartment in Wellington?", "hl fhb pa ip",
             "It is difficult. Many lenders decline units in buildings rated earthquake-prone (below 34% NBS) and some are cautious above that. We check the seismic report and strengthening plans before you offer."),
            ("I'm on a fixed-term government contract. Can I still borrow?", "hl fhb pa se",
             "Often yes, depending on how long the contract runs and your history in similar roles. Lender policy varies, so we choose the one that fits."),
            ("Can I refinance if my Wellington home has lost value?", "rf",
             "Possibly. Lower equity narrows your options, but a restructure or careful lender choice can still save money. We check the numbers after costs first."),
            ("Is Lower Hutt or Porirua better value for a first home?", "fhb",
             "They often give more house for the money, but check flood, liquefaction and insurance notes for each suburb. We compare lenders across the region."),
            ("Do Wellington rentals still stack up for investors?", "ip",
             "Demand is steady near universities, hospitals and the CBD, but older homes need Healthy Homes upgrades. We model lender rental assessments before you buy."),
            ("Can a consultant paid through their own company get a home loan?", "se",
             "Yes. Some lenders accept a shorter trading history for ongoing contracts. We present your income the way each lender assesses it."),
            ('Can I switch lenders if my Wellington apartment has a low seismic rating?', 'rf',
             "It can be difficult, because the new lender will check the building's rating and may decline. Restructuring with your current bank is sometimes the better option. We check both before you incur costs."),
        ],
    },
    "christchurch": {
        "factors": [
            ("TC1, TC2 and TC3 land", "hl fhb pa ip rf",
             "After the Canterbury earthquakes, residential land on the flat was mapped as Technical Category TC1, TC2 or TC3. TC3 land, and some TC2, can need geotechnical or engineering reports before a lender will commit, and foundation repairs come under closer scrutiny. We check the land category and repair records early so valuation and approval run smoothly."),
            ("Repair history and as-is properties", "hl fhb pa",
             "Many Christchurch homes were repaired after the quakes, some through the Natural Hazards Commission (formerly EQC) and some privately or as-is. Lenders want evidence that repairs were consented and done properly. A property sold as-is or with an over-cap claim history can still be financed, but the lender list is shorter."),
            ("Affordability draws first home buyers", "fhb pa hl",
             "Christchurch has been more affordable than Auckland or Wellington, which keeps first home buyer demand strong. Combining KiwiSaver withdrawals, the Kāinga Ora First Home Loan where eligible, and new-build exemptions can lower the deposit you need. We check eligibility and lender options before you start bidding."),
            ("Rolleston, Lincoln and Halswell new builds", "fhb hl ip pa",
             "Growth areas in Selwyn and southwest Christchurch, including Rolleston, Lincoln and Halswell, offer many new homes. New builds are exempt from LVR limits, which helps both first home buyers and investors. We plan the build contract and valuation timing with the lender."),
            ("Coastal suburbs and flood management", "hl rf ip",
             "Eastern suburbs such as New Brighton and Southshore, and some areas near the Heathcote and Avon rivers, carry flood management and coastal hazard notes. These affect insurance and lender appetite. We check the LIM and insurability before recommending a purchase or switch."),
            ("Investor yields", "ip rf",
             "Christchurch has offered stronger rental yields than many larger cities, which helps investors service loans under DTI limits. Lenders shade rental income differently and some are more comfortable with TC3 or older stock than others. We compare investor policy across lenders before you buy or restructure."),
            ("Trades and rebuild businesses", "se rf",
             "The rebuild left Canterbury with many self-employed builders, engineers and trades businesses. Lenders want to see stable trading, and some will use one year of financials or accountant-prepared figures. We match your business income to the lender most likely to accept it."),
            ("Accountants' figures and add-backs", 'se pa',
             'Canterbury self-employed borrowers often reinvest heavily or pay themselves a low salary, which can make accounts look thinner than the business really is. Some lenders allow add-backs such as depreciation and one-off costs. We work with your accountant so the income is presented in a way the lender will accept.'),
            ('Self-employed buyers in Selwyn growth areas', 'se fhb',
             'Many self-employed families buy new builds in Rolleston, Lincoln and Halswell. New-build exemptions can lower the deposit, but the lender still needs to accept your income history. We line up a lender that fits both the build and your accounts.'),
        ],
        "faqs": [
            ("Will a bank lend on TC3 land in Christchurch?", "hl fhb pa ip",
             "Yes, but expect the lender to want geotechnical or engineering information, especially for foundation repairs. We check the category and reports early so valuation and approval aren't delayed."),
            ("Can I buy a Christchurch house that was sold as-is?", "hl fhb pa",
             "Often, but fewer lenders will take it on. Evidence of the repair scope and a builder's or engineer's report usually decide it. We find the lender most comfortable with the property."),
            ("Is Christchurch a good place for first home buyers?", "fhb",
             "It has been more affordable than other main centres, and KiwiSaver, the First Home Loan and new-build exemptions can lower the deposit. We check eligibility first."),
            ("Can I refinance a Christchurch home on TC2 or TC3 land?", "rf",
             "Usually, but the new lender may want repair and land reports. We confirm the lender is comfortable before you incur switching costs."),
            ("Do Christchurch rentals suit investors under DTI limits?", "ip",
             "Stronger yields than many cities can help, but lenders shade rental income differently. We model each lender's assessment before you commit."),
            ("Can a self-employed tradie in Canterbury get a mortgage?", "se",
             "Yes. Some lenders accept one year of financials or accountant-prepared figures. We present your accounts to the lender that fits."),
            ('Should I refinance my Christchurch mortgage when my fixed rate ends?', 'rf',
             "It's worth comparing. Christchurch borrowers often get competitive offers from other lenders, but switching costs and land category checks matter. We compare the net benefit first."),
            ('How do lenders treat add-backs for self-employed buyers?', 'se pa',
             "Some lenders add back depreciation, one-off costs and some interest to your profit. Others don't. We choose the lender whose method gives a fair view of your income."),
        ],
    },
    "dunedin": {
        "factors": [
            ("Older villas and cold homes", "hl fhb pa rf",
             "Dunedin has some of New Zealand's oldest housing stock: villas, bungalows and character homes that can be cold, damp or under-insulated. Lenders and valuers look closely at condition, and a builder's report is worth getting. Some lenders allow extra borrowing for insulation and heating, which we can build into the loan."),
            ("Student flats in North Dunedin", "ip rf",
             "The University of Otago drives strong rental demand in North Dunedin. Student flats have high turnover and must meet Healthy Homes standards, and some lenders are wary of multi-tenancy or converted properties. We compare investor policy across lenders and structure the loan to suit the asset."),
            ("South Dunedin flood and groundwater risk", "hl fhb pa ip rf",
             "South Dunedin and nearby low-lying areas face flooding and rising groundwater, and the council has flagged them for long-term planning. That can affect insurance availability and lender appetite. We check hazard notes and insurability before you make an offer or switch lenders."),
            ("Hill suburbs and retaining walls", "hl fhb pa ip",
             "Many Dunedin homes sit on steep sections with retaining walls, slip history or difficult access. These appear on LIMs and builder's reports and can affect both insurance and valuation. We review them early so they don't delay settlement."),
            ("Relative affordability", "fhb pa hl",
             "Dunedin has been more affordable than most larger centres, so many first home buyers can get in with KiwiSaver and, where eligible, the Kāinga Ora First Home Loan. We check eligibility before you start bidding."),
            ("Health, education and small business income", "se pa",
             "Many Dunedin borrowers work for the hospital or the university, often on fixed-term or research contracts, or run small local businesses. Lenders differ on contract and self-employed income. We present your employment or accounts to the lender that suits it best."),
            ('Sole traders and small practices', 'se rf',
             'Dunedin has many sole traders, contractors and small professional practices. Main banks generally want two years of financials, but some lenders accept one year or GST returns with a strong trading history. We match your accounts to the lender most likely to approve, and look at refinancing if your current bank is assessing you harshly.'),
            ('Locums and medical contractors', 'se pa',
             'Doctors, nurses and allied health workers in Dunedin often work as locums or contractors. Some lenders have specific professional policies that recognise this income sooner. We know which lenders treat medical contractors favourably.'),
        ],
        "faqs": [
            ("Will a bank lend on an old Dunedin villa?", "hl fhb pa",
             "Yes, but expect the valuer to look closely at condition. A builder's report helps, and some lenders will fund insulation and heating as part of the loan."),
            ("Are North Dunedin student flats good investments?", "ip",
             "Demand is strong, but student flats need Healthy Homes compliance and some lenders are cautious about multi-tenancy. We match you to lenders comfortable with the property."),
            ("Does South Dunedin flood risk affect getting a mortgage?", "hl fhb pa ip rf",
             "It can, mainly through insurance. Lenders need full cover before they settle, so we check insurability and hazard notes early."),
            ("Can I refinance to pay for insulation and heating?", "rf",
             "Often yes, through a top-up with your current lender or as part of a switch. We compare both options after costs."),
            ("I'm on a fixed-term research contract. Can I buy in Dunedin?", "se pa fhb",
             "Often, depending on how long the contract runs and your history in similar roles. Lender policy varies, so we choose the right one."),
            ('Can a self-employed Dunedin borrower get a main bank mortgage?', 'se',
             'Yes, usually with two years of financials. If you have less, a non-bank lender can be a stepping stone back to a main bank.'),
        ],
    },
    "queenstown": {
        "factors": [
            ("Holiday homes and short-stay income", "ip hl rf pa",
             "Many Queenstown properties earn short-stay income, but lenders treat it cautiously. Some won't count it at all, and others shade it heavily or require a track record. Visitor accommodation also has district plan rules. We find lenders whose policy recognises short-stay income and check the property is set up correctly."),
            ("Serviced and managed apartments", "ip hl pa",
             "Hotel-style and managed apartments are common around Queenstown and Frankton, often with management agreements or restricted use. Many main banks decline or need a large deposit for them. We check the title, management agreement and lender appetite before you commit."),
            ("Seasonal and visa-holder income", "hl fhb pa se",
             "Tourism and hospitality employ many Queenstown residents, often on seasonal contracts or work visas. Lenders differ on how much seasonal income they count and which visas they accept. We match your employment and residency status to lenders whose policy fits."),
            ("The highest prices in the country", "fhb pa hl",
             "Queenstown Lakes has some of New Zealand's highest house prices, so DTI limits and deposit requirements bite hard. Couples often combine KiwiSaver, family help and new-build options to get in. We work through every lever before you start bidding."),
            ("Overseas buyer restrictions", "hl pa ip",
             "Most people who are not New Zealand citizens or residents can't buy existing homes under the Overseas Investment Act, with exceptions such as Australian and Singaporean citizens. Your residency status shapes both what you can buy and which lenders you can use. We confirm eligibility before you search."),
            ("Business owners in tourism and trades", "se rf",
             "Many Queenstown self-employed borrowers run tourism, construction or hospitality businesses with seasonal cashflow. Some lenders average income over two years and accept seasonal patterns. We present your accounts to lenders that understand the local economy."),
            ("Frankton, Shotover Country and Lake Hayes growth", "fhb hl rf",
             "New subdivisions around Frankton, Shotover Country, Lake Hayes Estate and Jack's Point have increased housing supply. New builds are exempt from LVR limits, which can lower the deposit needed. We plan the build contract and valuation timing with the lender."),
            ('Construction and trade businesses', 'se pa',
             "Queenstown's building boom has created many self-employed builders, project managers and trades businesses. Lenders want stable trading history and will look at your work pipeline. We present your accounts and contracts to lenders that understand construction cashflow."),
        ],
        "faqs": [
            ("Will lenders count Airbnb income on a Queenstown property?", "ip hl pa",
             "Some will, usually shaded and with a track record. Others won't count it at all. We find lenders whose short-stay policy suits the property."),
            ("Can I get a mortgage on a serviced apartment in Queenstown?", "ip pa",
             "It's possible but limited. Many main banks decline managed or hotel-style units, so expect a larger deposit and a specialist lender."),
            ("I'm on a work visa in Queenstown. Can I buy a home?", "fhb hl pa",
             "It depends on your visa type and the Overseas Investment Act. Some visa holders can't buy existing homes. We confirm your eligibility first."),
            ("Can I refinance a Queenstown holiday home?", "rf",
             "Often, if the new lender is comfortable with the property type and how you use it. Short-stay use and managed apartments narrow the options, so we check before you switch."),
            ("Can seasonal tourism business income qualify for a mortgage?", "se",
             "Yes, with the right lender. Some average two years of income and accept seasonal patterns."),
            ("Is a new build in Shotover Country or Lake Hayes a good first home?", "fhb",
             "It can be, since new builds are exempt from LVR limits. We plan for build timing and valuation at completion."),
            ('Should I refinance my Queenstown home when my fixed rate ends?', 'rf',
             "It's worth comparing lenders before the rollover. We look at rates, cashback and switching costs, and only recommend moving if it pays."),
            ('Can a Queenstown builder or tradie get a home loan?', 'se pa',
             'Yes. Lenders look at trading history and how stable your work pipeline is. We match your accounts to the lender that fits.'),
        ],
    },
    "napier-hawkes-bay": {
        "factors": [
            ("Cyclone Gabrielle land categories", "hl fhb pa ip rf",
             "After Cyclone Gabrielle in 2023, affected Hawke's Bay properties were placed in risk categories, and Category 3 land was offered buyouts. Lenders and insurers check which category a property is in and whether mitigation work is planned. We confirm the category and insurability before you make an offer or switch lenders."),
            ("Liquefaction and Art Deco heritage", "hl fhb pa ip",
             "Napier was rebuilt after the 1931 earthquake, and parts of the city and Hastings carry liquefaction risk. Heritage-listed Art Deco buildings may have limits on alterations. We review LIM notes and heritage listings early so they don't delay approval."),
            ("Orchard and seasonal income", "se pa hl",
             "Horticulture and viticulture are major employers across Hawke's Bay, with seasonal and contract income common. Lenders differ in how they average seasonal earnings and treat orchard or contracting businesses. We match your income pattern to lenders that understand it."),
            ("First home buyer value", "fhb pa",
             "Hawke's Bay prices have been more achievable than the main centres, so KiwiSaver withdrawals and, where eligible, the Kāinga Ora First Home Loan can go a long way. We check eligibility before you start bidding."),
            ("Rentals in Napier and Hastings", "ip rf",
             "Rental demand in Napier and Hastings has been firm, especially since the cyclone reduced housing supply. Investors are assessed under DTI limits and lender rental shading, and flood-affected areas need insurance checks. We model the deal across several lenders first."),
            ("Rebuild and repair after the cyclone", "rf hl se",
             "Many Hawke's Bay owners are still repairing or rebuilding, sometimes with insurance payouts or government support. Restructuring the loan, or a top-up for repairs, can be cheaper than other finance. We compare options after costs and check the repaired property suits the lender."),
            ('Wine, orchard and contracting businesses', 'se pa',
             "Many Hawke's Bay self-employed borrowers own vineyards, orchards or contracting businesses with uneven annual income, especially after cyclone disruption. Some lenders will average income or look past one poor year with a clear explanation. We present your accounts with that context so the lender sees the full picture."),
        ],
        "faqs": [
            ("Can I get a mortgage on a Category 2 property in Hawke's Bay?", "hl fhb pa ip",
             "Often, but lenders and insurers check the category and any mitigation plans. We confirm insurability and lender appetite before you commit."),
            ("Can I refinance a Hawke's Bay home repaired after Cyclone Gabrielle?", "rf",
             "Usually, if it can be insured and the repairs are documented. We check this before recommending a switch."),
            ("Will lenders count seasonal orchard income?", "se pa hl",
             "Many will, usually averaged over a period. Policy varies, so we choose the lender that fits your income pattern."),
            ("Is Napier or Hastings better for a first home?", "fhb",
             "Both can work. Check flood categories and liquefaction notes, and whether you're eligible for the First Home Loan. We compare options across both."),
            ("Are Hawke's Bay rentals worth it for investors?", "ip",
             "Demand has been firm since the cyclone, but insurance and flood categories matter. We model lender rental assessments before you buy."),
            ("Should I refinance my Hawke's Bay mortgage when my fixed term ends?", 'rf',
             "It's worth comparing, but insurance and land category checks apply if you switch. We confirm the new lender is comfortable before you incur costs."),
            ('Will a lender look past one bad year after the cyclone?', 'se',
             'Some will, if you can explain the dip and show recovery. We present your accounts with that context.'),
        ],
    },
    "palmerston-north": {
        "factors": [
            ("Defence postings at Linton and Ohakea", "hl fhb pa ip",
             "Linton Military Camp and RNZAF Base Ohakea bring many defence families to the Manawatū. Postings can mean buying now and renting the home out later. We structure the loan so it still works if you're posted elsewhere and the home becomes a rental."),
            ("Student rental demand", "ip rf",
             "Massey University and UCOL support steady rental demand around Hokowhitu, Fitzherbert and the city centre. Investors need Healthy Homes compliance and are assessed under DTI limits. We compare lender rental policy before you buy or restructure."),
            ("Affordable entry for first home buyers", "fhb pa hl",
             "Palmerston North has been one of the more affordable cities, so first home buyers can often combine KiwiSaver with the Kāinga Ora First Home Loan where eligible. We check eligibility and which participating lender suits you."),
            ("Logistics and distribution jobs", "pa fhb se",
             "The city is a major distribution hub, with many shift workers in warehousing and freight. Lenders treat overtime and allowances differently. We gather the right income history so your real pay is counted."),
            ("Older weatherboard housing", "hl rf fhb ip",
             "Many Palmerston North homes are older weatherboard builds that need insulation, heating or re-roofing. Some lenders will fund those improvements as part of the loan. We factor a builder's report into the plan."),
            ("Rural service businesses", "se rf",
             "Self-employed borrowers here often run agricultural contracting, rural supply or trade businesses with seasonal income. Some lenders average two years and accept add-backs. We present your accounts to lenders that understand rural cashflow."),
            ('Self-employed in health and education', 'se pa',
             'Palmerston North has many contractors and small practices linked to the hospital, Massey and the defence bases. Lenders differ on how quickly they recognise contract and self-employed income. We find the lender whose policy fits your history.'),
        ],
        "faqs": [
            ("I'm in the Defence Force. Can I buy in Palmerston North before a posting?", "hl fhb pa ip",
             "Yes. We structure the loan so it still works as a rental if you're posted away, and choose a lender comfortable with that plan."),
            ("Is Palmerston North good for first home buyers?", "fhb",
             "It has been one of the more affordable cities, so KiwiSaver and the First Home Loan can go further. We check eligibility first."),
            ("Do student rentals near Massey make good investments?", "ip",
             "Demand is steady, but Healthy Homes compliance matters and lenders shade rental income differently. We model the deal first."),
            ("Should I refinance my Palmerston North home to fund renovations?", "rf",
             "If equity allows, a top-up or switch can fund insulation or roofing at home-loan rates. We compare options after costs."),
            ("Will lenders count my warehouse overtime and shift allowances?", "pa se hl",
             "Most count some of it, based on history. We choose the lender that recognises your real pay."),
            ('Should I refinance my Palmerston North mortgage when my fixed rate ends?', 'rf',
             "It's worth comparing. We look at other lenders' rates, cashback and switching costs, and only recommend moving if it pays."),
            ('How long do I need to be self-employed to buy in Palmerston North?', 'se',
             'Main banks usually want two years of trading. Some lenders accept less if you have worked in the same industry before.'),
        ],
    },
    "nelson": {
        "factors": [
            ("Flood and slip history", "hl fhb pa ip rf",
             "Nelson Tasman has had serious flood and slip events in recent years, including the August 2022 storm that hit Atawhai and the Maitai valley. Affected properties may carry hazard notes that affect insurance and lender appetite. We check the LIM and insurability early."),
            ("Lifestyle blocks around Tasman", "hl rf pa",
             "Lifestyle properties around Richmond, the Moutere and Wakefield are popular, but larger blocks, rural water and septic systems can fall outside standard residential policy. We know which lenders are comfortable with rural-residential property."),
            ("Retirees and downsizers", "hl rf",
             "Nelson attracts many people moving for retirement. Lenders want a clear repayment plan when a loan runs past retirement age, such as the sale of another home or a shorter term. We present that plan up front."),
            ("Horticulture, seafood and seasonal income", "se pa fhb",
             "Apples, hops, vineyards and the seafood industry around Port Nelson employ many seasonal and contract workers, and many locals run their own businesses. Lenders differ on seasonal and self-employed income. We match you to a lender that fits."),
            ("Richmond growth and new builds", "fhb hl pa ip",
             "New subdivisions in Richmond and the Tasman fringe offer new builds that are exempt from LVR limits, helping first home buyers with smaller deposits. We plan the build contract and valuation timing with the lender."),
            ("Rental demand and yields", "ip rf",
             "Rental supply in Nelson is tight, and investors are assessed under DTI limits and lender rental shading. We compare investor policy across lenders before you buy or restructure."),
            ('Sole traders and lifestyle businesses', 'se rf',
             'Many Nelson Tasman locals run small businesses in tourism, trades, arts or food. Lenders want consistent trading, and some will accept one year or recent GST returns. We present your figures to the lender that suits them, and look at refinancing if your current bank has become a poor fit.'),
            ('Contractors in horticulture and marine', 'se pa',
             'Contractors in orchards, vineyards and the marine sector often have income that rises and falls through the year. Some lenders average it over two years. We match your pattern to the right lender.'),
        ],
        "faqs": [
            ("Does flood history affect getting a mortgage in Nelson?", "hl fhb pa ip",
             "It can, mainly through insurance. Lenders need full cover, so we check hazard notes and insurability before you offer."),
            ("Can I buy a lifestyle block in Tasman with a normal home loan?", "hl pa",
             "Often, if the land size and services fit residential policy. Otherwise a rural or specialist lender may suit. We check before you commit."),
            ("Can I get a mortgage close to retirement in Nelson?", "hl rf",
             "Yes, with a clear repayment plan. We set that out for the lender up front."),
            ("Can seasonal horticulture or fishing income get a home loan?", "se fhb pa",
             "Yes, with the right lender. Some average seasonal earnings over two years."),
            ("Should Nelson investors refinance?", "ip rf",
             "If equity has grown or your rate is rolling off, a restructure can lower costs or release equity. We check the net benefit first."),
            ('Can a self-employed Nelson borrower get a home loan?', 'se',
             'Yes. Main banks usually want two years of financials, and non-bank lenders can help if your history is shorter.'),
        ],
    },
    "whangarei-northland": {
        "factors": [
            ("Rural and lifestyle property", "hl rf pa ip",
             "Much of Northland is rural or lifestyle property with tank water, septic systems and long access roads. Lenders look closely at land size, services and whether the property is residential. We know which lenders are comfortable with rural-residential Northland property."),
            ("Building on Māori land", "hl fhb pa",
             "Whānau building on multiply-owned Māori land face a different lending path, because the land usually can't be mortgaged in the normal way. Specialist products and papakāinga arrangements exist, but they need careful planning. We help you work out the right pathway before you commit to a build."),
            ("Storm, slip and access risk", "hl fhb pa ip rf",
             "Northland was hit hard by Cyclone Gabrielle and other storms, with slips and road closures in many areas. Hazard notes and insurance availability can affect lender appetite. We check the LIM and insurability early."),
            ("Holiday homes in the Bay of Islands", "ip hl rf",
             "Bach and holiday-home ownership is common around Paihia, Russell and the east coast. Lenders treat short-stay income cautiously and some have limits on remote or holiday properties. We find lenders whose policy suits the property and how you use it."),
            ("First home buyers in Whangārei", "fhb pa",
             "Whangārei has been more affordable than Auckland, drawing first home buyers and commuters. KiwiSaver withdrawals and, where eligible, the Kāinga Ora First Home Loan can lower the deposit. We check eligibility first."),
            ("Self-employed and seasonal income", "se pa",
             "Many Northlanders run their own businesses in tourism, forestry, farming or trades, often with seasonal cashflow. Some lenders average two years of income and accept seasonal patterns. We present your accounts to the lender that fits."),
            ('Forestry, farming and tourism businesses', 'se rf',
             "Northland's self-employed borrowers often run forestry, farming, tourism or trade businesses with seasonal or uneven income. Some lenders average two years or accept a clear explanation for a weak year. We present your accounts to the lender that fits, and review your structure when you refinance."),
            ('Self-employed buyers of rural property', 'se hl',
             "Business owners buying rural or lifestyle property in Northland face two sets of checks: income and property type. We find lenders comfortable with both, so you aren't declined on one after passing the other."),
        ],
        "faqs": [
            ("Can I get a home loan to build on Māori land in Northland?", "hl fhb pa",
             "It's possible, but standard mortgages usually don't work on multiply-owned land. Specialist products and papakāinga arrangements exist. We help you find the right pathway."),
            ("Will a bank lend on a rural property with tank water and septic?", "hl pa ip se",
             "Usually, if the property is residential and the services are compliant. Larger or remote blocks may need a specialist lender."),
            ("Can I refinance a Northland property affected by Cyclone Gabrielle?", "rf",
             "Usually, if it can be insured and any damage is repaired. We check this before recommending a switch."),
            ("Is Whangārei a good place for a first home?", "fhb",
             "It has been more affordable than Auckland, and KiwiSaver and the First Home Loan can go further. We check eligibility first."),
            ("Will lenders count Bay of Islands holiday rental income?", "ip",
             "Some will, usually shaded and with a track record. We find lenders whose short-stay policy fits."),
            ("Can seasonal forestry or tourism business income qualify?", "se",
             "Yes, with the right lender. Some average income over two years and accept seasonal patterns."),
            ('Should I refinance my Northland mortgage when my fixed rate ends?', 'rf',
             "It's worth comparing, but rural property and storm history can limit which lenders will take it on. We check that before you switch."),
        ],
    },
}
